export * from "./work-shops-form-modal/work-shops-form-modal.component";
export * from "./benefit-deduction-form-modal/benefit-deduction-form-modal.component";
export * from "./tax-form-modal/tax-form-modal.component";
export * from "./educatio-evidences-form-modal/educatio-evidences-form-modal.component";
export * from "./educatio-fields-form-modal/educatio-fields-form-modal.component";
export * from "./employment-types-form-modal/employment-types-form-modal.component";
export * from "./organization-post-form-modal/organization-post-form-modal.component";
export * from "./payment-location-form-modal/payment-location-form-modal.component";
export * from "./employes-form-modal/employes-form-modal.component";
